### ISSUE TITLE
Failed to resolve: com.github.edubarr 

### ISSUE THREAD

**Issue by gelbertgel** [edubarr/header-decor#91]
When I add this to gradle, it fails:
`Failed to resolve: com.github.edubarr`

My project build.gradle:

```
buildscript {
    repositories {
        jcenter()
        google()
        maven {
            url 'https://maven.fabric.io/public'
        }
    }
    dependencies {

        classpath 'com.android.tools.build:gradle:3.1.3'
        classpath 'io.realm:realm-gradle-plugin:5.2.0'
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url 'https://maven.google.com/' }
        maven { url "https://jitpack.io" }
        google()
        flatDir {
            dirs 'libs'
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```
My app build gradle:

    implementation 'com.github.edubarr.header-decor/header-decor:0.2.8'

**Comment by oshamahue** [comment]
I think there is a problem with jitpack build so it is not  downloadable from jitpack. `ca.barrenechea.header-decor:header-decor:0.2.8` works for me so you can also use this until a new version is released to jitpack.

**Comment by oshamahue** [comment]
As I mentioned there is a problem at jitpack build system. https://github.com/jitpack/jitpack.io/issues/2837 .I have added a badge for jitpack so we will be able to see problems like this easier.

**Comment by starkej2** [comment]
Should be working now I think

**Comment by oshamahue** [comment]
It is still broken. I think jitpack will not be able to build it with the old build tools. A release needs to be made.

**Comment by starkej2** [comment]
Fine with me, but someone should probably test all of the changes since the last release first to make sure nothing got broken.

**Comment by oshamahue** [comment]
I can do it over the weekend. how was the testing done previously?

**Comment by edubarr** [comment]
I just tested with the sample app, as most of the functionality was easily observable through manual testing. We should think about getting a few unit tests in place to make sure things are behaving as expected.

**Comment by edubarr** [comment]
Another thing that just occurred to me is that we can release a `-SNAPSHOT` version of the library to test if the jitpack issue has been addressed. We should look into how to make it happen as I'm guessing jitpack should have some documentation on how to set it up.

**Comment by oshamahue** [comment]
actually we don't need to do anything. jitpack does itself. `  implementation 'com.github.edubarr:header-decor:master-SNAPSHOT'` should work out of the box.

**Comment by gelbertgel** [comment]
Thank you it is resolved!
